version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:8.7.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=txBxb3-0QO4R7-tFXvXqMKewt8
      - http.host=0.0.0.0
      - http.port=9200
      - http.cors.allow-origin='*'
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    # volumes:
    #   - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - express_elastic

  kibana:
    image: kibana:8.7.0
    # volumes:
    #   - ./kibana/data:/usr/share/kibana/data
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - express_elastic

  # express-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: express-app
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - express_elastic
  #   stdin_open: true
  #   tty: true
  #   restart: always

networks:
  express_elastic:
